;hi-res configuration settings for Fallout 2 CE

;##################################################################################################################
[MAIN]

; Set SCALE_2X=1 to scale the game x2.
; Note: This will increase the minimum resolution to from 640x480 to 1280x960.
SCALE_2X=1

; Set the Fullscreen resolution here.
SCR_WIDTH=640
SCR_HEIGHT=480

; Set WINDOWED=1 to enable windowed mode. 
WINDOWED=1

[IFACE]

; 0=map view sits above IFACE bar, 1=map extends to bottom and IFACE overlaps
IFACE_BAR_MODE=1

; 0=black, 1=metal grey, 2=leather, 3-6=alt metal, 7=alt leather, 8=metal brown
IFACE_BAR_SIDE_ART=8

; 0=extend from IFACE bar to screen edges, 1=extend from screen edges to IFACE bar
IFACE_BAR_SIDES_ORI=0

; 640=original width, 800=wider bar (requires f2_res.dat)
IFACE_BAR_WIDTH=640

[STATIC_SCREENS]

; 0=original size, 1=scale preserving aspect ratio, 2=stretch to fill
SPLASH_SCRN_SIZE=1

[MAPS]

; 0=hi-res map scroll edges enabled, 1=ignored
IGNORE_MAP_EDGES=0

