#ifndef SCAN_UNIMPLEMENTED_SFALL_H
#define SCAN_UNIMPLEMENTED_SFALL_H

// A copy-paste from sFall
// commit 930d1e8a032388c1989b0e9f7a469f570e44f621
// https://github.com/sfall-team/sfall
#include <string>

static const std::string sfall_metarules[] = {
    "add_extra_msg_file",
    "add_iface_tag",
    "add_g_timer_event",
    "add_trait",
    "art_cache_clear",
    "art_frame_data",
    "attack_is_aimed",
    "car_gas_amount",
    "combat_data",
    "create_win",
    "critter_inven_obj2",
    "dialog_message",
    "dialog_obj",
    "display_stats",
    "draw_image",
    "draw_image_scaled",
    "exec_map_update_scripts",
    "floor2",
    "get_can_rest_on_map",
    "get_combat_free_move",
    "get_current_inven_size",
    "get_cursor_mode",
    "get_flags",
    "get_ini_config",
    "get_ini_section",
    "get_ini_sections",
    "get_inven_ap_cost",
    "get_map_enter_position",
    "get_metarule_table",
    "get_object_ai_data",
    "get_object_data",
    "get_outline",
    "get_sfall_arg_at",
    "get_stat_max",
    "get_stat_min",
    "get_string_pointer",
    "get_terrain_name",
    "get_text_width",
    "get_window_attribute",
    "has_fake_perk_npc",
    "has_fake_trait_npc",
    "hide_window",
    "interface_art_draw",
    "interface_overlay",
    "interface_print",
    "intface_hide",
    "intface_is_hidden",
    "intface_redraw",
    "intface_show",
    "inventory_redraw",
    "item_make_explosive",
    "item_weight",
    "lock_is_jammed",
    "loot_obj",
    "message_box",
    "metarule_exist",
    "npc_engine_level_up",
    "obj_is_openable",
    "obj_under_cursor",
    "objects_in_radius",
    "outlined_object",
    "real_dude_obj",
    "reg_anim_animate_and_move",
    "remove_timer_event",
    "set_spray_settings",
    "set_can_rest_on_map",
    "set_car_intface_art",
    "set_combat_free_move",
    "set_cursor_mode",
    "set_drugs_data",
    "set_dude_obj",
    "set_fake_perk_npc",
    "set_fake_trait_npc",
    "set_flags",
    "set_iface_tag_text",
    "set_ini_setting",
    "set_map_enter_position",
    "set_object_data",
    "set_outline",
    "set_quest_failure_value",
    "set_rest_heal_time",
    "set_worldmap_heal_time",
    "set_rest_mode",
    "set_scr_name",
    "set_selectable_perk_npc",
    "set_terrain_name",
    "set_town_title",
    "set_unique_id",
    "set_unjam_locks_time",
    "set_window_flag",
    "show_window",
    "signal_close_game",
    "spatial_radius",
    "string_compare",
    "string_find",
    "string_format",
    "string_to_case",
    "tile_by_position",
    "tile_refresh_display",
    "unjam_lock",
    "unwield_slot",
    "win_fill_color",
    "validate_test"
};

struct SfallOpcodeInfo {
    fallout::opcode_t opcode;
    std::string name;
};

static struct SfallOpcodeInfo opcodeInfoArray[] = {
    { 0x15a, "set_pc_base_stat" },
    { 0x15b, "set_pc_extra_stat" },
    { 0x15c, "get_pc_base_stat" },
    { 0x15d, "get_pc_extra_stat" },
    { 0x15e, "set_critter_base_stat" },
    { 0x15f, "set_critter_extra_stat" },
    { 0x160, "get_critter_base_stat" },
    { 0x161, "get_critter_extra_stat" },
    { 0x163, "get_year" },
    { 0x16c, "key_pressed" },
    { 0x171, "force_encounter" },
    { 0x175, "set_dm_model" },
    { 0x176, "set_df_model" },
    { 0x177, "set_movie_path" },
    { 0x189, "set_perk_name" },
    { 0x18a, "set_perk_desc" },
    { 0x18b, "set_pipboy_available" },
    { 0x190, "get_perk_available" },
    { 0x192, "set_critter_current_ap" },
    { 0x195, "set_weapon_knockback" },
    { 0x196, "set_target_knockback" },
    { 0x197, "set_attacker_knockback" },
    { 0x198, "remove_weapon_knockback" },
    { 0x199, "remove_target_knockback" },
    { 0x19a, "remove_attacker_knockback" },
    { 0x19d, "set_sfall_global" },
    { 0x19e, "get_sfall_global_int" },
    { 0x19f, "get_sfall_global_float" },
    // { 0x1a5, "inc_npc_level" }, // implemented
    { 0x1aa, "set_xp_mod" },
    { 0x1ac, "get_ini_setting" },
    { 0x1bb, "set_fake_perk" },
    { 0x1bc, "set_fake_trait" },
    { 0x1bd, "set_selectable_perk" },
    { 0x1c1, "has_fake_perk" },
    { 0x1c2, "has_fake_trait" },
    { 0x1c5, "set_critter_hit_chance_mod" },
    { 0x1c7, "set_critter_skill_mod" },
    { 0x1c9, "set_critter_pickpocket_mod" },
    { 0x1dc, "show_iface_tag" },
    { 0x1dd, "hide_iface_tag" },
    { 0x1de, "is_iface_tag_active" },
    { 0x1e1, "set_critical_table" },
    { 0x1e2, "get_critical_table" },
    { 0x1e3, "reset_critical_table" },
    { 0x1e4, "get_sfall_arg" },
    { 0x1e5, "set_sfall_return" },
    { 0x1eb, "get_ini_string" },
    { 0x1ec, "sqrt" },
    { 0x1ed, "abs" },
    { 0x1ee, "sin" },
    { 0x1ef, "cos" },
    { 0x1f0, "tan" },
    { 0x1f1, "arctan" },
    { 0x1f2, "set_palette" },
    { 0x1f3, "remove_script" },
    { 0x1f4, "set_script" },
    { 0x1f5, "get_script" },
    { 0x1f7, "fs_create" },
    { 0x1f8, "fs_copy" },
    { 0x1f9, "fs_find" },
    { 0x1fa, "fs_write_byte" },
    { 0x1fb, "fs_write_short" },
    { 0x1fc, "fs_write_int" },
    { 0x1fd, "fs_write_int" },
    { 0x1fe, "fs_write_string" },
    { 0x1ff, "fs_delete" },
    { 0x200, "fs_size" },
    { 0x201, "fs_pos" },
    { 0x202, "fs_seek" },
    { 0x203, "fs_resize" },
    { 0x204, "get_proto_data" },
    { 0x205, "set_proto_data" },
    { 0x207, "register_hook" },
    { 0x208, "fs_write_bstring" },
    { 0x209, "fs_read_byte" },
    { 0x20a, "fs_read_short" },
    { 0x20b, "fs_read_int" },
    { 0x20c, "fs_read_float" },
    { 0x20d, "list_begin" },
    { 0x20e, "list_next" },
    { 0x20f, "list_end" },
    { 0x216, "set_critter_burst_disable" },
    { 0x217, "get_weapon_ammo_pid" },
    { 0x218, "set_weapon_ammo_pid" },
    { 0x219, "get_weapon_ammo_count" },
    { 0x21a, "set_weapon_ammo_count" },
    { 0x21e, "get_mouse_buttons" },
    { 0x224, "create_message_window" },
    { 0x228, "get_attack_type" },
    { 0x229, "force_encounter_with_flags" },
    { 0x22a, "set_map_time_multi" },
    { 0x22b, "play_sfall_sound" },
    { 0x22d, "create_array" },
    { 0x22e, "set_array" },
    { 0x22f, "get_array" },
    { 0x230, "free_array" },
    { 0x231, "len_array" },
    { 0x232, "resize_array" },
    { 0x233, "temp_array" },
    { 0x234, "fix_array" },
    { 0x235, "string_split" },
    { 0x236, "list_as_array" },
    { 0x237, "atoi" },
    { 0x238, "atof" },
    { 0x239, "scan_array" },
    { 0x23a, "get_tile_fid" },
    { 0x23b, "modified_ini" },
    { 0x23c, "get_sfall_args" },
    { 0x23d, "set_sfall_arg" },
    // { 0x241, "get_npc_level" }, // implemented
    { 0x242, "set_critter_skill_points" },
    { 0x243, "get_critter_skill_points" },
    { 0x24e, "substr" },
    { 0x24f, "strlen" },
    { 0x250, "sprintf" },
    { 0x251, "charcode" },
    // 0x252 // RESERVE
    { 0x253, "typeof" },
    { 0x254, "save_array" },
    { 0x255, "load_array" },
    { 0x256, "array_key" },
    { 0x257, "arrayexpr" },
    // 0x258 // RESERVED for array
    // 0x259 // RESERVED for array
    { 0x25a, "reg_anim_destroy" },
    { 0x25b, "reg_anim_animate_and_hide" },
    { 0x25c, "reg_anim_combat_check" },
    { 0x25d, "reg_anim_light" },
    { 0x25e, "reg_anim_change_fid" },
    { 0x25f, "reg_anim_take_out" },
    { 0x260, "reg_anim_turn_towards" },
    { 0x261, "metarule2_explosions" },
    { 0x262, "register_hook_proc" },
    { 0x263, "power" },
    { 0x264, "log" },
    { 0x265, "exponent" },
    { 0x266, "ceil" },
    { 0x267, "round" },
    // 0x268 RESERVE
    // 0x269 RESERVE
    // 0x26a RESERVE
    { 0x26b, "message_str_game" },
    { 0x26c, "sneak_success" },
    { 0x26d, "tile_light" },
    { 0x26e, "obj_blocking_line" },
    { 0x26f, "obj_blocking_tile" },
    { 0x270, "tile_get_objs" },
    { 0x271, "party_member_list" },
    { 0x272, "path_find_to" },
    { 0x273, "create_spatial" },
    { 0x274, "art_exists" },
    { 0x275, "obj_is_carrying_obj" },
    // universal opcodes
    { 0x276, "sfall_func0" },
    { 0x277, "sfall_func1" },
    { 0x278, "sfall_func2" },
    { 0x279, "sfall_func3" },
    { 0x27a, "sfall_func4" },
    { 0x27b, "sfall_func5" },
    { 0x27c, "sfall_func6" },

    { 0x27d, "register_hook_proc_spec" },
    { 0x27e, "reg_anim_callback" },
    { 0x27f, "div" },

    { 0x280, "sfall_func7" },
    { 0x281, "sfall_func8" }
};

#endif